### PR TITLE
Update dependencies, include 64bit arch

### PR DESCRIPTION
**Pull request by squidpunch**
This may only be an issue when using frank in Ruby Motion, but when I attempt to run my frank features with the latest version of RubyMotion the skeleton doesnt get included because the 64-bit arch isnt included.  I think this is a guard clause since apps will require 64-bit architecture to be included starting in Feb 2015.

In any event this makes it possible for me to use frank again on my project, so I'd like to see it merged if it isnt a breaking change for other users, etc.

### CODE REVIEW

**Comment by CMTaylor** [comment]
I’m trying to build my Frank-enabled App with Xcode 6 for iOS 8 and need this 64-bit version of Frank. The problem is that I’m very “lame” with GIT and don’t really understand what I need to do to get these changes.  I have a clone of https://github.com/moredip/Frank here: https://github.com/CMTaylor/Frank but I don’t see the pull request referenced below. I’m not clear what https://github.com/TestingWithFrank/Frank is and how it relates to https://github.com/moredip/Frank, but I do see the https://github.com/TestingWithFrank/Frank/pull/37 under the “TestingWithFrank” GIT repository.

Can someone please advise me on what steps to take to get this essential 64-bit fix into my Frank?

I also have some potentially useful additions to Frank in my clone that I’d like to make available back to the Frank community, but again my GIT knowledge is too weak to know how to do this. I’m also now unsure as to which “Frank” is the “real Frank” (moredip or TestingWithFrank). Again, GIT assistance would be much appreciated.

Thanks,
Martin

**Comment by CMTaylor** [comment]
squidpunch duplicated this pull request on my fork of Frank. I merged his changes with mine and then fixed a couple of issues where his work was not complete. I generated a new pull request #40 for the combination of squidpunch's work and my work, so you could take just that one instead of this one.

**Comment by moredip** [comment]
This got resolved independently by PR #42

**Comment by squidpunch** [comment]
closing, looks like @CMTaylor pulled in my changes to a new PR that was merged.

**Pull request closed without merging**
